name: Deploy Rick.Zhou's Blog

on:
  - push

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Build 📦
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EMAIL: 944268618@qq.com
          USERNAME: Rick.Zhou
          REPO: github.com/rick-chou/react-awesome.git
        run: |

          echo node version
          node -v

          echo npm version
          npm -v

          echo yarn version
          yarn -v

          # overrides field not working
          # use yarn instand
          # npm install
          yarn

          cd projects/@rick-awesome

          npm ci
          npm run build

          cd dist
          cp index.html 404.html

          # git init
          # git config --global user.email $EMAIL
          # git config --global user.name $USERNAME
          # git remote add origin https://$ACCESS_TOKEN@$REPO

          # git checkout -b gh-pages
          # git add .
          # git commit -m "🌈 @rickzhou/awesome"
          # git push -f --set-upstream origin gh-pages

      - name: Upload 📦
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: projects/@rick-awesome/dist
          token: ${{ secrets.ACCESS_TOKEN }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Deploy 🚀
        # https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
          full_commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.rick-chou.github.com'
