name: react-flowchart

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Push 📦
        env:
          EMAIL: 944268618@qq.com
          USERNAME: rick zhou
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd projects/@rick-flow

          git init
          git config --global user.email $EMAIL
          git config --global user.name $USERNAME
          git remote set-url origin https://rick-chou:$ACCESS_TOKEN@github.com/rick-chou/react-flowchart.git

          git checkout -b main
          git add .
          git commit -m "🌈 @rickzhou/flowchart"
          git push --set-upstream origin main
